name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.60.133
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}  # Private key here
          port: 22
          debug: true
          script: |
             cd CI-CD
             git pull 
             npm install
             npm run build
             pm2 start web | pm2 restart web
            