name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 15.207.111.230
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            cd /home/ubuntu/githubactions || { echo "Directory not found"; exit 1; }
            git pull origin main
            npm install
            npm run build
            # Optionally skip dev or run in background
            npm run dev &