name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.60.133
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}  # Private key here
          port: 22
          debug: true
          script: |
              if [ -d CI-CD ];then
                cd CI-CD 
              else   
                git clone https://github.com/Ashishlakhimale23/CI-CD.git
                cd CI-CD
              fi
              git pull origin main  
              npm install
              npm run build
              pm2 start web | pm2 restart web
            