name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: 13.201.167.40
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }}  # Private key here
          port: 22
          debug: true
          script: |
             cd CI-CD
             git pull 
             npm install
             npm run build
             npm run dev
            